const DATA = {
  keyandmouse: [
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 3000000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "dien thoai",
      image: `app-img.png`,
      price: 23666666,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 23666666,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 23666666,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 23666666,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 23666666,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 55500000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 3420000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 34500000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 65400000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 456400000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 45645644,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 530456000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 23666666,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 2,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 23666666,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 88800000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 7700000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 67800000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 67800000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 678760000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 597870000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 7890000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },

    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 7890000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 56600000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },

    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 3450000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
    {
      nameStore: "keyandmouse",
      id: 3,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 78760000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
  ],
  phone: [
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 53000000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
  ],
  watch: [
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 53000000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
  ],
  speaker: [
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 53000000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
  ],
  Laptop: [
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 53000000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
  ],
  tivi: [
    {
      nameStore: "keyandmouse",
      id: 0,
      quantity: 1,
      productType: "bàn phím",
      title: "MonsGeek M1 QMK Black AKKO Switch v3 Cream Yellow Pro",
      image: `app-img.png`,
      price: 53000000,
      detail:
        "  Thiết kế	75% có núm xoay Kết nối	USB Type-C to USB, có thể tháo rời Keycap	Keycap PBT Double-Shot / OEM profile ,Loại switch	AKKO Switch v3 – Cream Yellow Pro Led,	LED nền RGB / South-Facing Mạch Xuôi (Backlit, 4028 SMD LED dạng SMD) với nhiều chế độHotswap 5 pin, mạch xuôi (South-Facing) – Hỗ trợ QMK / VIA Hỗ trợ	NKRO / Multimedia / Macro / Khóa phím windows Phụ kiện	Cover che bụi – Dây cáp – Phụ kiện backup Tương thích	Windows / MacOS / Linux Kích thước	332x147x33mm Trọng lượng	1.962kg ",
      trademark: "Akko",
    },
  ],
};
export default DATA;
